name: SayHello

on:
   push:
     branches:
       - develop
       - main
       - release

   pull_request:
     branches:
       - main
       - develop
       - release

       
jobs:
  detect-branch:                       
     runs-on: ubuntu-latest            

     steps:
       - name: Get Your Code
         uses: actions/checkout@v4   
          
       - name: Say Hello Develop
         if: ${{ github.ref == 'refs/heads/develop' }}
         run: echo "Hello, develop!"
         
       - name: Say Hello Main
         if: ${{ github.ref == 'refs/heads/main' }}
         run: echo "Hello, main!"
